> 서킷브레이커의 기본 컨셉은 아래 글을 참고하자.  
> https://hyeon9mak.github.io/spring-circuit-breaker/

## 기존 서킷브레이커 사용 방법

[Spring Cloud Circuit Breaker Docs](https://spring.io/projects/spring-cloud-circuitbreaker) 에서 
제공하는 인터페이스로 factory 를 직접 하나 생성하여 사용하는 방법과

```kotlin
fun findGroup(groupId: GroupId): Group {
    val circuitBreaker = factory.create("name")
    return circuitBreaker.run(
        run = {
            return groupFinder.find(groupId)
        },
        fallback = { exception ->
            return DefaultGroup()
        }
    )
}
```

Spring AOP 를 이용하는 방법이 있다.

```kotlin
@CircuitBreaker(name = "name", fallbackMethod: "failback")
fun findGroup(groupId: GroupId): Group {
    return groupFinder.find(groupId)
}

fun fallback(groupId: GroupId, e: Exception): Group {
    return DefaultGroup()
}
```

대부분 Spring AOP 방식을 채택하고 있다.

> circuit 이 open 되는 경우 CallNotPermittedException 이 발생한다.

<br>

## 문제점

### 1. 컴파일 단계에서 실수를 알아차리기 어렵다.

위 예시에서 의도적으로 오타를 남겨두었다. 눈치 챘었는가?

![image](https://github.com/user-attachments/assets/4b5abfcd-6cd3-4d16-8375-04196c6b9833)

`fallbackMethod` 는 문자열을 통해 관리하므로 인간이 실수하기 너무나 쉽다. 
컴파일 단계에서 예외를 발생시켜주지 않으므로 런타임이 되어서야 문제가 있음을 인지할 수 있다.

### 2. CallNotPermittedException 에 대해 알아야한다.

`CallNotPermittedException` 은 Resilience4j 가 만든 CustomException 이다. 

[https://resilience4j.readme.io/docs/getting-started-4#circuitbreaker](https://resilience4j.readme.io/docs/getting-started-4#circuitbreaker)

저걸 인지하고 CircuitBreaker 를 사용하는 개발자가 얼마나 될까?

### 3. Open Fallback 만 처리하기가 번거롭다.

일반적인 예외 상황 말고, circuit 이 open 된 경우에만 처리하고 싶을 땐?
모든 상황에서 항상 fallback 메서드로 동작이 넘어오기 때문에, 어떤 이유로 넘어온 것인지 확인하는 코드가 필요해진다.

```kotlin
fun fallback(groupId: GroupId, e: Exception): Group {
    when (e) {
        is CallNotPermittedException -> return DefaultGroup()
        else -> throw e
    }
}
```

### 4. 꼭 외부 클래스로 만들어서 사용해야만한다.

Spring AOP 의 특성으로, 메인이 되는 비즈니스 로직이 담긴 클래스와 같은 공간에 서킷브레이커 메서드를 만들 수 없다.

<br>

## 해결방법

크게 3가지가 필요하다.

1. 메서드를 circuit breaker 로 감싸주는 주체 
2. circuit breaker 에 이름을 부여할 수 있는 기능 
3. fallback 메서드와 연결할 수 있는 기능

최종적으로 아래와 같은 형상이면 어떨까?

```kotlin
fun findGroup(groupId: GroupId) = circuit("name") {
    groupFinder.find(groupId)
}.fallback {
    DefaultGroup()
}.fallbackIfOpen {
    // ...
}
```
```kotlin
// circuit 이름을 지정하지 않으면 자동 부여

fun findGroup(groupId: GroupId) = circuit {
    groupFinder.find(groupId)
}.fallback {
    DefaultGroup()
}.fallbackIfOpen {
    // ...
}
```

### 구현

```kotlin
interface CircuitBreaker {
    fun <T> run(name: String, block: () -> T): T
}
```
```kotlin
// spring cloud circuit breaker 를 직접 사용하지 않고, 한차례 감춤.
// 전달 받은 로직 블록을 circuit breaker 로 감싸서 실행.
// circuit 이 open 되는 경우 다르게 처리할 수 있도록 try-catch

class StandardCircuitBreaker(
    val factory: SpringCloudCircuitBreakerFactory
) : CircuitBreaker {

    override fun <T> run(name: String, block: () -> T): T {
        try {
            val circuitBreaker = factory.create(name)
        return circuitBreaker.run(block)
        } catch (e: Exception) {
            if (e is CallNotPermittedException) throw CircuitOpenException()
            else throw e
        }
    }
}
```
```kotlin
// spring 이 뜰 때 singleton 으로 인스턴스를 하나 받아서 갖고 있다가 전달해주는 클래스

class DefaultCircuitBreakerProvider(
    val circuitBreaker: CircuitBreaker
) {
    fun get() = circuitBreaker
}
```
```kotlin
// 기본 파라미터를 활용해서 이름과 circuit breaker 주입 생략

fun <T> circuit(
    name: String - apiPath(),
    circuitBreaker: CircuitBreaker = DefaultCircuitBreakerProvider.get(),
    block: () -> T,
): Result<T> {
    return runCatching {
        circuitBreaker.run(name, block)
    }
}

fun <T> Result<T>.fallback(block: () -> T): Result<T> =
  if (this.isSuccess) { this }
  else { runCatching { block() } }

fun <T> Result<T>.fallbackIfOpened(block: () -> T): Result<T> = when(this.exceptionOrNull()) {
  is CircuitBreakerOpenedException -> runCatching { block() }
  else -> this
}
```

<br>

## 소소한 문제점

`Result.failure` 내부 값 Exception 을 바로 사용하고 싶을 경우 문제가 발생한다.

```kotlin
class KotlinResultAdvice {

    fun beforeBodyWrite(body: Any): Any {
        when (body) {
            is Result -> return body.getOrThrow()
            else -> return body
        }
    }
}
```

아마도 대부분은 body 가 `body = Result(Group)` 형태로 넘어올거라 기대하지만, 실제로는 `body = Group` 형태로 넘어온다. 
또한 exception 도 `body = Result(Failure(NotFoundException))` 이 아니라 `body = Failure(NotFoundException)` 이 넘어온다.

심지어 Failure 는 Result 의 internal class 이기 때문에, 직접 다룰 수 있는 방법이 아예 없다.

왜 이런 일이 발생할까? 이유는 `Result` 가 `value class` 이기 때문이다.

```kotlin
value class Result(
    val value: Any
)
```

`value class` 는 컴파일 단계에서 최적화로 인해 내부 프로퍼티만 남게 된다.

`value class` 는 Kotlin 코드 사이에서 주고 받을 땐 문제가 없다.
다만 우리는 Spring + Kotlin 을 사용중이다. Spring 대부분은 Java 로 이루어져 있다.
Spring(Java) ↔︎ Kotlin 사이 `value class` 가 오고가며 문제가 발생하게 된 것.

어떻게 이 문제를 해결할 수 있을까? 의외로 간단하다. 다시 `Result` 로 감싸면 됨.

```kotlin
class KotlinResultAdvice {

    fun beforeBodyWrite(body: Any): Any {
        return Result.success(body).getOrThrow()
    }
}
```

<br>

## References

- [서킷브레이커 사용 방식 개선하기 | 당근 SERVER 밋업 2회](https://youtu.be/ThLfHtoEe1I?feature=shared)
